# BUSINESS SCIENCE UNIVERSITY
# PYTHON FOR GENERATIVE AI COURSE
# MULTI-AGENTS (AGENTIAL SUPERVISION)
# ***

# CHALLENGE 4: CREATE AN APPLICATION THAT HELPS USERS ANALYZE STOCKS USING THE 01_stock_analysis_supervisor_agent

# DIFFICULTY: ADVANCED

# SPECIFIC ACTIONS:
#  1. Should produce plots on demand
