# BUSINESS SCIENCE UNIVERSITY
# PYTHON FOR GENERATIVE AI COURSE
# MULTI-AGENTS (AGENTIAL SUPERVISION)
# ***

# CHALLENGE 5: CREATE AN APPLICATION THAT HELPS USERS ANALYZE THE CUSTOMERS, PRODUCTS, AND TRANSACTIONS AND CREATE COMPELLING MARKETING EMAIL COPY USING THE 04_customer_analytics_team

# DIFFICULTY: ADVANCED

# SPECIFIC ACTIONS:
#  1. App should have chat memory 
#  2. Suggest any improvements
